### ISSUE TITLE
66: insufficient priority on token creation

### ISSUE THREAD

**Issue by istrau2** [Bitcoin-com/wormhole-sdk#76]
I am attempting to create a token using the following code:

```
wormhole.PayloadCreation.managed(ecosystem, propertyPrecision, previousId, category, subcategory, name, url, data);
```
The payload is successfully hitting the server but the getting rejected with 

> 66: insufficient priority

I've tried using very high fees (up to 0.1 BCH) and still getting rejected. Note, that this is on the BCH testnet.

**Comment by christroutner** [comment]
Thanks for filing an issue @istrau2. Another user recently reported this error on the Wormhole SDK Discord channel:
https://discord.gg/zRnTaVu

Be sure that the address you're using for the example has both WHC **and** BCH. You can get both here:
https://developer.bitcoin.com/faucets

This error was thrown because the wallet does not have enough BCH to execute the transaction.

**Comment by istrau2** [comment]
@christroutner I am pretty sure it does. Here it is: https://www.blocktrail.com/tBCC/address/mmt7iQ3M7LpQjytursLtnRdF2mk6v2799N

**Comment by christroutner** [comment]
I'm leaving this issue open. We should add a PR to this code base to catch this type of error and add a suggestion, to indicate to the user that they need to add BCH to their address.

**Comment by istrau2** [comment]
BCH and WHC. In my case it was WHC that was missing.

**Comment by christroutner** [comment]
Closing this issue. If this happens again, please leave a comment and tag me and I'll re-open.
